### ISSUE TITLE
Hashes calculated before files copied in TaskHelper.php

### ISSUE THREAD

**Issue by GeraintEdwards** [yootheme/starter-utils#1] opened 2024-10-01 10:27 UTC
In the code

`
        foreach ($finder->files() as $file) {
            $old = hash_file('sha256', 'build/' . $file->getRelativePathname());
            $new = hash_file('sha256', $file);

            if ($old === $new) {
                continue;
            }

            $fs->dumpFile('build/' . $file->getRelativePathname(), $file->getContents());
        }
`
You are calculating the hash values before the files have been dumped.  I believe this is causing the error in your StarterPlugin

**Comment by hendrikbehncke** [comment] 2024-10-02 09:32
Duplicate of yootheme/starter-plugin#3
Resolved with https://github.com/yootheme/starter-utils/commit/ce5f263119c4ca9241fa358f892b98e4f84c8800

**Closed as completed by hendrikbehncke** 2024-10-02 09:32 UTC

**Comment by GeraintEdwards** [comment] 2024-10-02 09:54
Is there a way to configure the start-plugin to pick up the develop branch of starter-utils?

**Comment by hendrikbehncke** [comment] 2024-10-02 13:39
You could specify the exact commit hash in the composer.json.

But there is also a new release now to fix the starter-plugin
